version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - josephworks
  ignore:
  - dependency-name: org.apache.logging.log4j:log4j-core
    versions:
    - 2.14.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
  - dependency-name: net.md-5:SpecialSource
    versions:
    - 1.8.6
  - dependency-name: org.apache.maven:maven-artifact
    versions:
    - 3.6.3
