image: gradle:alpine

variables:
    GIT_SUBMODULE_STRATEGY: recursive

build:
    script:
        - gradle build
        - gradle dumpLibs
    artifacts:
        paths:
            - build/libs/
            - build/libraries/